
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LESH
 */
public class Exercise13 extends javax.swing.JFrame {

    ArrayList<String> l2 = new ArrayList<String>();
    DefaultTableModel modelo;
    String numpiezas = "";

    public Exercise13() {

        initComponents();
        initcomponents2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btn = new javax.swing.JButton();
        dias = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adver = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulación");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btn.setText("Empezar Simulación");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        dias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diasKeyTyped(evt);
            }
        });

        jLabel1.setText("Simular por");

        jLabel2.setText("dias");

        jButton1.setText("Mostrar resultados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(122, 122, 122)
                        .addComponent(adver, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(adver, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void initcomponents2() {
        this.setLocationRelativeTo(null);
    }
    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        Metodo m = new Metodo();
        modelo = new DefaultTableModel();
        modelo.addColumn("Dia");
        modelo.addColumn("Pieza");
        modelo.addColumn("Hora llegada");
        modelo.addColumn("T llegada torno");
        modelo.addColumn("T tarda torno");
        modelo.addColumn("H salida torno");
        modelo.addColumn("Transporte inspeccion");
        modelo.addColumn("H llegada inspeccion");
        modelo.addColumn("T inspector");
        modelo.addColumn("Salida inspeccion");
        Object[] o = new Object[10];
        o[0] = "Dia";
        o[1] = "Pieza";
        o[2] = "Hora llegada";
        o[3] = "T llegada torno";
        o[4] = "T tarda torno";
        o[5] = "H salida torno";
        o[6] = "Transporte inspeccion";
        o[7] = "H llegada inspeccion";
        o[8] = "T inspector";
        o[9] = "Salida inspeccion";
        modelo.addRow(o);
        tabla.setModel(modelo);
        if (!dias.getText().isEmpty()) {
            for (int y = 1; y <= Integer.parseInt(dias.getText()); y++) {
                ArrayList l = m.datos();
                o[0] = y;
                for (int i = 0; i < l.size(); i++) {
                    StringTokenizer tokens = new StringTokenizer(l.get(i).toString());
                    int j = 1;
                    while (tokens.hasMoreTokens()) {
                        o[j] = tokens.nextToken();
                        j++;
                    }

                    numpiezas = o[1].toString();
                    modelo.addRow(o);
                }
                o[0] = "Dia";
                o[1] = "Pieza";
                o[2] = "Hora llegada";
                o[3] = "T llegada torno";
                o[4] = "T tarda torno";
                o[5] = "H salida torno";
                o[6] = "Transporte inspeccion";
                o[7] = "H llegada inspeccion";
                o[8] = "T inspector";
                o[9] = "Salida inspeccion";
                modelo.addRow(o);
                l2.add(numpiezas);
            }
        }else{
             JOptionPane.showMessageDialog(null, "Ingrese dias a simular", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnActionPerformed

    private void diasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diasKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();
            adver.setText("Ingrese solo numeros");

        }
        if (Character.isDigit(c)) {

            adver.setText("");

        }

    }//GEN-LAST:event_diasKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (l2.size() > 0) {
            JFrame resultados=new JFrame();
            resultados.setSize(500,400);
            Resultados s = new Resultados(l2);
            resultados.add(s);
                    resultados.setTitle("Ventas");
                    resultados.setVisible(true);
                    resultados.setLocationRelativeTo(null);
            l2.clear();
             modelo = new DefaultTableModel();
        modelo.addColumn("Dia");
        modelo.addColumn("Pieza");
        modelo.addColumn("Hora llegada");
        modelo.addColumn("T llegada torno");
        modelo.addColumn("T tarda torno");
        modelo.addColumn("H salida torno");
        modelo.addColumn("Transporte inspeccion");
        modelo.addColumn("H llegada inspeccion");
        modelo.addColumn("T inspector");
        modelo.addColumn("Salida inspeccion");
        tabla.setModel(modelo);
        } else {

            JOptionPane.showMessageDialog(null, "Iniciar una simulacion", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercise13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercise13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercise13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercise13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercise13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adver;
    private javax.swing.JButton btn;
    private javax.swing.JTextField dias;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
